### ISSUE TITLE
How to set the autopick?

### ISSUE THREAD

**Issue by ly19811105** [theBGuy/UpdatedMapHack#1]
I have been changed the below setting as true. But the bot not auto pickup anything .Is there any wrong on this .I just want auto pickit .thanks.

Config.ManualPlayPick = true; // If set to true and D2BotMap or D2BotManualPlay entry script is used, will enable picking in manual play.

**Comment by theBGuy** [comment]
Do you have the file tools/PickThread.js and did you change ManualPlayPick to true in the right configuration file?

**Comment by ly19811105** [comment]
Yes, I had the file and changed as below . Please help on this.thanks.

Path: d2bs\kolbot\libs\config\ManualPlay.js

Config.ManualPlayPick = true; // If set to true and D2BotMap or D2BotManualPlay entry script is used, will enable picking in manual play.

**Comment by theBGuy** [comment]
Are you using the default pickit file, or did you add your own?

**Comment by ly19811105** [comment]
I just download the latest blizzhackers/kolbot zip file and this repo . Unzip them and all used default one. Nothing change except change Config.ManualPlayPick = true; please help check .thanks.

**Comment by ly19811105** [comment]
Have you tried the latest version of Kolbot? you can find the issue.

this is found in Kolbot  and it work .
i deleted "&& item.itemType !== 4" in Pickit.js and now it works. lol. - maybe my pickit worked all the time, but i always was looking at picking up gold to check if it works.
